name: Hub

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run Hub
      run: hub version && hub pr list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
