name: Prepare Release

on:
  pull_request:
    branches: ["master"]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.head_ref, 'release/v')"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Check existing release
      run: |
        TAG=${GITHUB_REF#release/}
        if hub release -f "%T:%s" | grep -e "^${TAG}:$" >/dev/null; then
          echo ${TAG} is already published
          exit 1
        fi
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Build for Windows
      run: |
        make release GOOS=windows GOARCH=amd64 VERSION="${GITHUB_REF#refs/tags/}"
    - name: Build for Darwin
      run: |
        make release GOOS=darwin GOARCH=amd64 VERSION="${GITHUB_REF#refs/tags/}"
    - name: Build for linux
      run: |
        make release GOOS=linux GOARCH=amd64 VERSION="${GITHUB_REF#refs/tags/}"
