name: Prepare Release

on:
  pull_request:
    branches: ["release/*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Env
      run: |
        echo ${GITHUB_REF}
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Build for Windows
      run: |
        make release GOOS=windows GOARCH=amd64 VERSION="${GITHUB_REF#refs/tags/}"
    - name: Build for Darwin
      run: |
        make release GOOS=darwin GOARCH=amd64 VERSION="${GITHUB_REF#refs/tags/}"
    - name: Build for linux
      run: |
        make release GOOS=linux GOARCH=amd64 VERSION="${GITHUB_REF#refs/tags/}"
