name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Build for Windows
      run: |
        make release GOOS=windows GOARCH=amd64 VERSION=${GITHUB_REF}
    - name: Build for Darwin
      run: |
        make release GOOS=darwin GOARCH=amd64 VERSION=${GITHUB_REF}
    - name: Build for linux
      run: |
        make release GOOS=linux GOARCH=amd64 VERSION="${GITHUB_REF}"
    - name: Upload
      run: |
        hub release edit "${GITHUB_REF}" -a build/hello-windows-amd64.zip -a build/hello-darwin-amd64.zip -a build/hello-linux-amd64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
