name: Test

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_type == push || github.event.pull_request.head.fork || !startsWith(github.head_ref, 'release/v')
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Run Test
      run: make test
    - name: Build
      run: make build
    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: ${{ github.workspace }}/build/*/hello
